language: java
# use Java 8
jdk:
- openjdk8


sudo: false

script:
 - mvn test
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  email: carlos.junior@aluno.uepb.edu.br
  email: priscylla.amaral@aluno.uepb.edu.br
  email: adoniscomp@gmail.com
  
# cache the build tool's caches
#cache:
#  directories:
#  - $HOME/.m2
