language: java
# use Java 8
jdk:
- oraclejdk8


sudo: false

script: mvn clean package
 

notifications:
  email: carlos.junior@aluno.uepb.edu.br
  email: priscylla.amaral@aluno.uepb.edu.br
  email: adoniscomp@gmail.com
  
# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
